### ISSUE TITLE
No such file or directory: './data/TACoS/train.json'

### ISSUE THREAD

**Issue by jingmingshi** [Huntersxsx/RaNet#2]
I don't find train.json fil, could you help me?

**Comment by Huntersxsx** [comment]
Thanks for your reminder. The dataset files can be found at https://github.com/microsoft/2D-TAN/tree/master/data and the extracted features can be found at https://rochester.app.box.com/s/8znalh6y5e82oml2lr7to8s6ntab6mavhttps://rochester.app.box.com/s/8znalh6y5e82oml2lr7to8s6ntab6mav

**Comment by Huntersxsx** [comment]
> I don't find train.json fil, could you help me?

Thanks for your reminder. The dataset files can be found at https://github.com/microsoft/2D-TAN/tree/master/data and the extracted features can be found at https://rochester.app.box.com/s/8znalh6y5e82oml2lr7to8s6ntab6mav/folder/137471266949
