### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by xmc-andy** [Huntersxsx/RaNet#3]
I try to solve the issue by setting cudnn.enabled=false, change the version of cuda, and I try to reduce the num of workers and batch_size. But the error still occurs. Have you encountered same problems?
```
`Traceback (most recent call `last):
  File "moment_localization/train.py", line 313, in <module>
    scheduler=scheduler)
  File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/core/engine.py", line 53, in train
    state['optimizer'].step(closure)
  File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/optim/adam.py", line 58, in step
    loss = closure()
  File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/core/engine.py", line 42, in closure
    loss, output = state['network'](state['sample'])
  File "moment_localization/train.py", line 169, in network
    prediction, map_mask = model(textual_input, textual_mask, visual_input)
  File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/models/ranet.py", line 25, in forward
    vis_h, txt_h = self.encoder_layer(visual_input, textual_input, textual_mask) 
  File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/models/feature_encoder/encoder.py", line 139, in forward
    vis_frame = self.frame_encoder(visual_input)  # B, C, T
  File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/models/feature_encoder/encoder.py", line 44, in forward
    vis_h = torch.relu(self.vis_conv(visual_input))
  File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
  0%|   `
```

**Comment by Huntersxsx** [comment]
> 

Maybe your pytorch  version and cuda version are not matched, try to download matched versions from ( https://pytorch.org/get-started/previous-versions/#v110 ).
Or you can refer to ( https://github.com/NVIDIA/tacotron2/issues/109#issuecomment-471940890 ) for detailed solutions.

**Comment by Huntersxsx** [comment]
> I try to solve the issue by setting cudnn.enabled=false, change the version of cuda, and I try to reduce the num of workers and batch_size. But the error still occurs. Have you encountered same problems?
> 
> ```
> `Traceback (most recent call `last):
>   File "moment_localization/train.py", line 313, in <module>
>     scheduler=scheduler)
>   File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/core/engine.py", line 53, in train
>     state['optimizer'].step(closure)
>   File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/optim/adam.py", line 58, in step
>     loss = closure()
>   File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/core/engine.py", line 42, in closure
>     loss, output = state['network'](state['sample'])
>   File "moment_localization/train.py", line 169, in network
>     prediction, map_mask = model(textual_input, textual_mask, visual_input)
>   File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/models/ranet.py", line 25, in forward
>     vis_h, txt_h = self.encoder_layer(visual_input, textual_input, textual_mask) 
>   File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/models/feature_encoder/encoder.py", line 139, in forward
>     vis_frame = self.frame_encoder(visual_input)  # B, C, T
>   File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gigigi/LJQ/RaNet/moment_localization/../lib/models/feature_encoder/encoder.py", line 44, in forward
>     vis_h = torch.relu(self.vis_conv(visual_input))
>   File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gigigi/anaconda3/envs/torch1/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
>   0%|   `
> ```

Maybe your pytorch version and cuda version are not matched, try to download matched versions from ( https://pytorch.org/get-started/previous-versions/#v110 ).
Or you can refer to ( https://github.com/NVIDIA/tacotron2/issues/109#issuecomment-471940890 ) for detailed solutions.
