### ISSUE TITLE
an error???

### ISSUE THREAD

**Issue by onlyonewater** [Huntersxsx/RaNet#4]
`RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.`
when I run the code, an error happened, how to fix it?

**Comment by Huntersxsx** [comment]
> `RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.` when I run the code, an error happened, how to fix it?

I didn't meet the problem in my experiment. This error can occur when passing a non-contiguous input tensor to a cuDNN function.  To fix this error, you can try ensuring that your input tensors are contiguous before passing them to cuDNN functions. You can do this by calling the .contiguous() method on your input tensors. 
`input = input.contiguous()`
